{
  lib,
  stdenvNoCC,
  fetchurl,
  unzip,
  neoforgeServers,
  fabricServers,
  quiltServers,
}:

let
  # CF modpack loader IDs use dotted versions ("21.1.224"); nix-minecraft
  # server attrs use underscored ones ("21_1_224").
  attrVersion = lib.replaceStrings [ "." ] [ "_" ];

  # Loader types we can resolve to a nix-minecraft server package set.
  # Legacy Forge isn't in nix-minecraft, so forge-based modpacks land here
  # with serverPackage = null and the user must wire their own server jar.
  loaderToServerSet = {
    neoforge = neoforgeServers;
    fabric = fabricServers;
    quilt = quiltServers;
  };

  # Pinned copy of itzg's curated client-only slug list. itzg ships this
  # at /image/cf-exclude-include.json inside docker-minecraft-server and
  # auto-loads it during AUTO_CURSEFORGE installs. We mirror the same
  # default. Override via the cfExcludeInclude argument.
  defaultCfExcludeInclude = fetchurl {
    name = "cf-exclude-include.json";
    url = "https://raw.githubusercontent.com/itzg/docker-minecraft-server/a44c7170412d489f51360f0641c84f525ad6acce/files/cf-exclude-include.json";
    sha256 = "sha256-V8m2M7//cj2gDZRCvkrDVsoy4yeOw3Sp6tl6TPIvEMw=";
  };

  fetchCurseForgeModpack =
    {
      # Path to a local CurseForge modpack ZIP (or a derivation/store path
      # produced by fetchurl). Provides manifest.json + overrides/.
      src,
      # Path to a JSON lockfile with the schema:
      #   {
      #     "minecraft": "1.21.1",
      #     "loader": { "type": "neoforge", "version": "21.1.224" },
      #     "files": [{ "pid", "fid", "slug", "filename", "sha1", "url", "side" }]
      #   }
      # `side` is one of "server" | "client" | "both" (derived by
      # nix-curseforge-genlocks from CF API gameVersions tags).
      # Generated by `nix-curseforge-genlocks <zip-or-url> locks.json`.
      locks,
      # Which side to assemble. "server" excludes side="client" entries,
      # "client" excludes side="server" entries, "both" includes everything.
      side ? "server",
      # Path to a cf-exclude-include.json file (same schema as
      # itzg/docker-minecraft-server's files/cf-exclude-include.json).
      # Mods whose CF slug appears in `.globalExcludes` are dropped from
      # the assembled output. Mods listed in `.globalForceIncludes` bypass
      # the side-based and slug-based filters.
      # Defaults to a pinned copy of itzg's upstream list. Override with
      # your own `pkgs.fetchurl`-fetched file (or set to null to disable).
      cfExcludeInclude ? defaultCfExcludeInclude,
      # Extra exclusions on top of side + cf-exclude-include filters. List
      # of project IDs (integers), CF slugs (strings), or jar filenames
      # (strings) to forcibly drop. Use for mods that aren't covered by
      # itzg's curated list but still need exclusion.
      extraExcludes ? [ ],
      # Counterpart to extraExcludes: list of pids/slugs/filenames to
      # forcibly include (overrides side + slug filters). Mirrors itzg's
      # CF_FORCE_INCLUDE_MODS.
      extraForceIncludes ? [ ],
      ...
    }@args:

    assert lib.assertMsg (builtins.elem side [
      "server"
      "client"
      "both"
    ]) "'side' must be one of: server, client, both";

    let
      locksData = lib.importJSON locks;
      pname = args.pname or "curseforge-pack";
      version = args.version or "";

      mcAttr = attrVersion locksData.minecraft;
      loaderAttr = attrVersion locksData.loader.version;
      serverAttr = "${locksData.loader.type}-${mcAttr}-${loaderAttr}";
      serverSet = loaderToServerSet.${locksData.loader.type} or null;
      serverPackage = if serverSet != null then serverSet.${serverAttr} or null else null;

      # Filter lockfile entries by requested side, the cf-exclude-include
      # slug list, and user-supplied extra excludes/includes.
      includedFiles =
        let
          excludeSide =
            if side == "server" then "client"
            else if side == "client" then "server"
            else null;

          cfData = if cfExcludeInclude == null then { } else lib.importJSON cfExcludeInclude;
          cfGlobalExcludes = cfData.globalExcludes or [ ];
          cfGlobalForceIncludes = cfData.globalForceIncludes or [ ];

          # Build a lookup set keyed by stringified pid, slug, or filename.
          # Each entry in the user-supplied list may be any of the three.
          mkLookup = entries: builtins.listToAttrs (
            map (e: { name = toString e; value = true; }) entries
          );
          matchesAny = lookup: m:
            (lookup.${toString m.pid} or false)
            || (lookup.${m.slug or ""} or false)
            || (lookup.${m.filename} or false);

          excludeLookup = mkLookup (cfGlobalExcludes ++ extraExcludes);
          forceIncludeLookup = mkLookup (cfGlobalForceIncludes ++ extraForceIncludes);

          isSideExcluded = m: excludeSide != null && (m.side or "both") == excludeSide;
          isExcluded = m: isSideExcluded m || matchesAny excludeLookup m;
          isForceIncluded = m: matchesAny forceIncludeLookup m;
        in
        builtins.filter (m: isForceIncluded m || !(isExcluded m)) locksData.files;

      # Per-mod content-addressed FOD via fetchurl. Identical {sha1} across
      # modpacks resolves to the same /nix/store path → cross-modpack sharing.
      mkModDrv =
        m:
        fetchurl {
          name = m.filename;
          url = m.url;
          sha1 = m.sha1;
        };

      mods = map mkModDrv includedFiles;

      drv = stdenvNoCC.mkDerivation {
        inherit pname version src;
        nativeBuildInputs = [ unzip ];

        unpackPhase = ''
          runHook preUnpack

          if [ -d "$src" ]; then
            cp -r "$src" pack-src
            chmod -R u+w pack-src
          else
            mkdir -p pack-src
            unzip -q "$src" -d pack-src
          fi

          runHook postUnpack
        '';

        buildPhase = ''
          set -euo pipefail
          runHook preBuild

          mkdir -p out/mods

          ${lib.concatMapStringsSep "\n" (m: ''
            ln -s ${mkModDrv m} out/mods/${lib.escapeShellArg m.filename}
          '') includedFiles}

          if [ -d pack-src/overrides ]; then
            cp -r pack-src/overrides/. out/
          fi

          runHook postBuild
        '';

        installPhase = ''
          runHook preInstall
          mkdir -p $out
          cp -r out/. $out/
          runHook postInstall
        '';

        passthru = {
          inherit mods serverPackage serverAttr;
          inherit (locksData) minecraft loader;
          locks = locksData;

          # Add files (e.g. side-mods from Modrinth) on top of the assembled
          # modpack. Mirrors fetchPackwizModpack/fetchModrinthModpack.
          addFiles =
            files:
            stdenvNoCC.mkDerivation {
              inherit (drv) pname version;
              src = null;
              dontUnpack = true;
              dontConfig = true;
              dontBuild = true;
              dontFixup = true;

              installPhase = ''
                cp -as "${drv}" $out
                chmod u+w -R $out
              ''
              + lib.concatLines (
                lib.mapAttrsToList (name: file: ''
                  mkdir -p "$out/$(dirname "${name}")"
                  cp -as "${file}" "$out/${name}"
                '') files
              );

              passthru = {
                inherit (drv)
                  mods
                  locks
                  minecraft
                  loader
                  serverPackage
                  serverAttr
                  ;
              };
              meta = drv.meta or { };
            };
        };
      };
    in
    drv;
in
fetchCurseForgeModpack
